### PR TITLE
Test against lowest dependencies

### PR DESCRIPTION
**Pull request by dbu**
Rebased #102 on current master and pushed to our repository.

### CODE REVIEW

**Comment by dbu** [comment]
i just notice that i rebased on master instead of 1.1...

i suggest we get this to work for 1.2 and then update the cmf bundles to require 1.2. there are important bugfixes to be had in 1.2 anyways...

**Comment by dbu** [comment]
@WouterJ what do you say if we only care about 1.2 which will become stable in the next two weaks? after that, we can also bump the minimum jackalope version for all cmf bundles that say something about jackalope.

**Comment by lsmith77** [comment]
+1

**Comment by dbu** [comment]
@WouterJ can we say "good enough" for this one?

**Comment by WouterJ** [comment]
@dbu as long as the 1.1 bugs are going to be fixed, I'm fine with merging lowest deps tests to 1.2.

**Pull request merged**
