### PR TITLE
Update phpcr/phpcr-api-tests

### PR DESCRIPTION
**Pull request by gabriel-caruso**
As asked @dbu in [phpcr/phpcr-api-tests#185](https://github.com/phpcr/phpcr-api-tests/pull/185#issuecomment-343391586)

### CODE REVIEW

**Comment by dbu** [comment]
phpcr-api-tests has been merged meanwhile. if you want to continue on this, please rebase once #153 is merged to avoid conflicts (i am working on php 7.2 support which requires changing occurences of `each`)

**Comment by gabriel-caruso** [comment]
@dbu Ok. As soon as you merge #153, I rebase

**Comment by dbu** [comment]
things have been merged and i tagged a release 1.3.2 with this. (phpunit upgrade is an internal detail that should not affect any users, thus i did not want to wait with tagging)

**Comment by dbu** [comment]
right, no point in keeping this branch. do you plan to do a PR to update to phpunit 6 in this repository as well?

**Comment by gabriel-caruso** [comment]
I'll make it :smile:

**Pull request closed without merging**
