### PR TITLE
Test against lowest dependencies

### PR DESCRIPTION
**Pull request by WouterJ**

### CODE REVIEW

**Comment by WouterJ** [comment]
@dbu can you please help me on this? The 2 jackalope PRs currently prevents from implementing lowest-dep tests in the CMF.

**Comment by dbu** [comment]
i just restarted the tests. when i checkout 1.1 locally and composer update, the tests pass for me. or maybe we need to tag another phpcr-api-tests and upgrade to that.

if that does not help, i suggest we make the minimal version thing only on master - we hopefully release jackalope 1.2 very soon now. not much missing anymore.

**Comment by WouterJ** [comment]
Using the minimal version thing only on master means we cannot add any lowest dep tests to the CMF bundles (as they all depent on 1.1).

**Comment by dbu** [comment]
continued in #105

**Pull request closed without merging**
