### PR TITLE
verify that copy of binary data works

### PR DESCRIPTION
**Pull request by lsmith77**
related to https://github.com/jackalope/jackalope-doctrine-dbal/pull/299

### CODE REVIEW

**Comment by dbu** [comment]
i checked the situation with the multivalue property with just one value and it looks a lot like its a jackrabbit bug with fixtures. i guess we need to skip this test with jackrabbit and see if we find a bug report for it.

**Comment by dbu** [comment]
and the same with the empty multivalue: looks like jackrabbit is not very exact when importing :-(

**Comment by dbu** [comment]
lukas, ok if i mark the tests as skipped or am i missing something? the fixtures are loaded with the jack.jar, so pure java. there is a slight chance its just the fixture loading part of jackrabbit that is to blame, but whichever it is, its not something we can solve it here.

**Comment by lsmith77** [comment]
+1

**Pull request merged**
